- library/Notifications/Widget/ItemList/IncidentListItem.php
> IncidentListItem: Render object names as anchor only when it is a subject link

- application/controllers/ContactsController.php
- application/controllers/EventRulesController.php
When switching to another tab in `col1` while `col2` is active, `col2` must also be closed, as it is not related to the currently active tab in `col1`.
> Add data base target `_main` to controller index action tabs

- library/Notifications/Common/Database.php
This should determine automatically if the backend resource is named after the module name.
> Database: Use module name as default backend name

- library/Notifications/Model/Timeperiod.php
- library/Notifications/Widget/Calendar.php
- library/Notifications/Widget/Calendar/BaseGrid.php
- library/Notifications/Widget/Calendar/Controls.php
- library/Notifications/Widget/Calendar/DayGrid.php
- library/Notifications/Widget/Calendar/ExtraEntryCount.php
- library/Notifications/Widget/Calendar/MonthGrid.php
- library/Notifications/Widget/Calendar/WeekGrid.php
- library/Notifications/Widget/Schedule.php
- public/css/calendar.less
- public/css/form.less
> Show additional daily appointments link

- library/Notifications/Widget/Calendar.php
- library/Notifications/Widget/Calendar/MonthGrid.php
- library/Notifications/Widget/Calendar/WeekGrid.php
> Calendar: Make `$url` nullable

- .github/workflows/php.yml
- application/controllers/ContactController.php
- application/controllers/EventRuleController.php
- application/controllers/IncidentsController.php
- application/forms/EscalationConditionForm.php
- application/forms/EscalationRecipientForm.php
- application/forms/RemoveEscalationForm.php
- library/Notifications/Web/Control/SearchBar/ObjectSuggestions.php
- library/Notifications/Widget/Detail/IncidentQuickActions.php
- library/Notifications/Widget/EventRuleConfig.php
- phpstan-baseline-7x.neon
- phpstan-baseline-8x.neon
- phpstan-baseline-by-php-version.php
- phpstan-baseline-standard.neon
- phpstan-baseline.neon
- phpstan.neon
> Github Actions: Add Phpstan

- application/controllers/ContactsController.php
- application/forms/ChannelForm.php
- application/forms/EscalationRecipientForm.php
- library/Notifications/Model/AvailableChannelType.php
- library/Notifications/Model/Behavior/HasAddress.php
- library/Notifications/Model/Channel.php
- library/Notifications/Web/Form/ContactForm.php
- library/Notifications/Widget/ItemList/ChannelListItem.php
- library/Notifications/Widget/ItemList/ContactListItem.php
- phpstan-baseline-7x.neon
- phpstan-baseline-8x.neon
- phpstan-baseline-standard.neon
- https://github.com/Icinga/icinga-notifications/pull/108
- https://github.com/Icinga/icinga-notifications/pull/142
> Use `available_channel_type` table data to create channelForm

- library/Notifications/Common/Icons.php
- library/Notifications/Widget/ItemList/IncidentHistoryListItem.php
> IncidentHistoryListItem: Fix icon for `rule_matched` event

- application/forms/EntryForm.php
Entry duration should be shorter than their frequency for recurrent entries.
resolves #139
> EntryForm: Validate entry duration against its frequency

- library/Notifications/Model/Behavior/ObjectTags.php
- library/Notifications/Model/ObjectExtraTag.php
- library/Notifications/Model/ObjectIdTag.php
- library/Notifications/Web/Control/SearchBar/ObjectSuggestions.php
- phpstan-baseline-standard.neon
> ObjectTags: Remove superfluous table name prefix from the column definition

- library/Notifications/Widget/Calendar/BaseGrid.php
- phpstan-baseline-standard.neon
- public/css/calendar.less
> Improve longer appointment style

- library/Notifications/Widget/Calendar.php
- library/Notifications/Widget/Calendar/Controls.php
- public/css/calendar.less
> Provide more intuitive calendar controls

- application/controllers/EventController.php
- application/controllers/EventsController.php
- application/controllers/IncidentController.php
- application/controllers/IncidentsController.php
- library/Notifications/Common/Database.php
- library/Notifications/Model/Behavior/IdTagAggregator.php
- library/Notifications/Model/Event.php
- library/Notifications/Model/Incident.php
- library/Notifications/Model/Objects.php
- library/Notifications/Widget/Detail/IncidentDetail.php
fixes #153
requires https://github.com/Icinga/ipl-orm/pull/128, https://github.com/Icinga/ipl-orm/pull/126 and https://github.com/Icinga/ipl-orm/pull/124
> Fix inefficient list views which render object names

- library/Notifications/Widget/Detail/IncidentDetail.php
- library/Notifications/Widget/ItemList/IncidentHistoryListItem.php
> IncidentDetail: Use relation `incindent.object` instead of `event.object`

- library/Notifications/Common/Icons.php
- library/Notifications/Model/Event.php
- library/Notifications/Model/Incident.php
- library/Notifications/Model/IncidentHistory.php
- library/Notifications/Model/Objects.php
- library/Notifications/Widget/Detail/EventDetail.php
- library/Notifications/Widget/Detail/IncidentDetail.php
- library/Notifications/Widget/Detail/IncidentQuickActions.php
- library/Notifications/Widget/IconBall.php
- library/Notifications/Widget/ItemList/EventListItem.php
- library/Notifications/Widget/ItemList/IncidentHistoryListItem.php
- public/css/common.less
targets https://github.com/Icinga/icinga-notifications-web/issues/157
> Event and Incident History improvements

- application/controllers/EventController.php
- application/controllers/IncidentsController.php
- library/Notifications/Widget/Detail/IncidentDetail.php
- library/Notifications/Widget/ItemList/IncidentHistoryListItem.php
- library/Notifications/Widget/ItemList/IncidentListItem.php
- public/css/common.less
> Move source icon in incident detail to the header

- application/forms/ChannelForm.php
Instead of rendering default values as placeholders, render them as element values.
> ChannelForm: Render default values as element values

- application/controllers/IncidentsController.php
The default sort of `Incident` model and controller must match.
> IncidentsController: Use `severity` as default sort and fix `Opened On`

- library/Notifications/Hook/ObjectsRendererHook.php
- library/Notifications/Model/Objects.php
- library/Notifications/Widget/Detail/EventDetail.php
- library/Notifications/Widget/Detail/IncidentDetail.php
- library/Notifications/Widget/ItemList/EventList.php
- library/Notifications/Widget/ItemList/IncidentList.php
- phpstan-baseline-standard.neon
resolves #132 
Blocked by: #155, #166
requires: https://github.com/Icinga/ipl-web/pull/217
> Hook implementation for event object display names

- application/controllers/ContactGroupController.php
- application/controllers/ContactGroupsController.php
- application/controllers/ContactsController.php
- application/controllers/EventRulesController.php
- application/controllers/SchedulesController.php
- application/forms/ContactGroupForm.php
- configuration.php
- library/Notifications/Common/Links.php
- library/Notifications/Model/Contact.php
- library/Notifications/Model/Contactgroup.php
- library/Notifications/Web/Form/ContactForm.php
- library/Notifications/Widget/ItemList/ContactGroupList.php
- library/Notifications/Widget/ItemList/ContactGroupListItem.php
- library/Notifications/Widget/ItemList/ContactListItem.php
- library/Notifications/Widget/MemberSuggestions.php
- public/css/common.less
resolves https://github.com/Icinga/icinga-notifications-web/issues/174
> Contactgroup configuration

- library/Notifications/Common/Icons.php
- library/Notifications/Model/Event.php
- library/Notifications/Widget/Detail/EventDetail.php
- library/Notifications/Widget/ItemList/EventListItem.php
> Support new event types

- application/forms/ContactGroupForm.php
The `ContactGroupForm` was missing a required condition to ensure that only memberships of the given group are going to get deleted.
Fixes: https://github.com/Icinga/icinga-notifications-web/issues/217
> ContactGroup: Fix contact deletion

- library/Notifications/ProvidedHook/Notifications/ObjectsRenderer.php
This column is required to fetch further relations
> ObjectsRenderer: Add missing `id` column

- library/Notifications/Web/Control/SearchBar/ObjectSuggestions.php
These columns should only be shown if explicitly given by user. Previously, columns with a similar suffix were also found, e.g. the search for `id` also showed `uuid` as search suggestion.
> ObjectSuggestions: Fix exotic columns match

- doc/03-Configuration.md
- doc/06-Desktop-Notifications.md
> doc: Mention required apache mods for desktop notifications

- library/Notifications/Daemon/Server.php
- library/Notifications/ProvidedHook/SessionStorage.php
* This isn't necessary anymore due to https://github.com/Icinga/icinga-notifications/pull/239
> Don't limit browser_session.user_agent to 4096 chars

- application/controllers/ScheduleController.php
> ScheduleController: Fix title for rotation modal

- library/Notifications/Widget/Detail/IncidentDetail.php
> IncidentDetail: Don't render `Object Tags` section if no tags are available

- library/Notifications/Widget/Timeline.php
- library/Notifications/Widget/Timeline/Rotation.php
- public/css/timeline.less
- public/js/schedule.js
> Make rotation title clickable and editable

- application/forms/ChannelForm.php
- application/forms/ContactGroupForm.php
- application/forms/MoveRotationForm.php
- application/forms/RotationConfigForm.php
- application/forms/SaveEventRuleForm.php
- application/forms/ScheduleForm.php
- application/forms/SourceForm.php
- library/Notifications/Model/Rotation.php
- library/Notifications/Web/Form/ContactForm.php
- library/Notifications/Widget/Detail/IncidentQuickActions.php
* Re: https://github.com/Icinga/icinga-notifications-web/issues/226#issuecomment-2695054673
The more precisely we write our timestamps, the less race conditions happen to the Go daemon's incremental config update mechanism if two users change something during the same second.
php > var_dump((int) (new DateTime())->format("Uv"));
int(1741607923054)
php > var_dump(time() * 1000);
int(1741607928000)
php >
> Don't cut off milliseconds from current-time-in-milliseconds

- library/Notifications/Widget/TimeGrid/Timescale.php
- library/Notifications/Widget/Timeline.php
- public/css/timeline.less
> Schedules: Add timescale and time indicator

- library/Notifications/Widget/ItemList/ContactGroupListItem.php
- library/Notifications/Widget/ItemList/ContactListItem.php
> Handle unicode in contact and contact group names

- application/forms/ChannelForm.php
- application/forms/ScheduleForm.php
- application/forms/SourceForm.php
- library/Notifications/Common/Database.php
The Go daemon's incremental config update mechanism regularily selects only config updates newer than the last known one.
This change ensures config rows having ascending changed_at, so nothing gets lost even if two users click during the same few ms. (E.g. CockroachDB allows nodes' clocks to differ by 7ms.)
closes https://github.com/Icinga/icinga-notifications/pull/288
closes https://github.com/Icinga/icinga-notifications/pull/237
```
mysql> -- create in web
mysql> select changed_at from source;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    7
Current database: notifications
+---------------+
| changed_at    |
+---------------+
| 1742577440317 |
+---------------+
1 row in set (0,07 sec)
mysql> update source set …
```
> Ensure new/updated rows having a changed_at greater than all previous ones

- library/Notifications/Hook/ObjectsRendererHook.php
Otherwise, the link is opened in the same container (_self).
> ObjectsRendererHook: Always use `_next` as `data-base-target`

- application/forms/ChannelForm.php
- library/Notifications/Common/Database.php
If the database's character set is not set correctly, the decoding of the config attributes may fail. For that case an error message will be rendered in the form. There will also be a docs entry to prevent that.
Closes #271
> Handle config decoding errors from DB charset issues

- library/Notifications/Widget/TimeGrid/Timescale.php
- public/css/timeline.less
Fixes the issues mentioned in https://github.com/Icinga/icinga-notifications-web/pull/292
> Timescale: Improve the visibility

- application/controllers/ChannelsController.php
- application/forms/ChannelForm.php
fixes #225 
- https://github.com/Icinga/icingaweb2/pull/5370
- https://github.com/Icinga/ipl-web/pull/284
> ChannelForm: Show message intead of stacktrace when no channel type found

- library/Notifications/Widget/TimeGrid/BaseGrid.php
- library/Notifications/Widget/TimeGrid/DynamicGrid.php
- library/Notifications/Widget/Timeline.php
- library/Notifications/Widget/Timeline/FutureEntry.php
- public/css/timeline.less
> Timeline: Visualize future rotations

- application/forms/ScheduleForm.php
> Improve the ScheduleForm
