application/forms/EntryForm.php

EntryForm: Remove hourly frequency

---

library/Notifications/Widget/Detail/IncidentQuickActions.php

Unmanage should downgrade the contact to a subscriber role

---

library/Notifications/Model/IncidentHistory.php

References Icinga/icinga-notifications#163 and is a sibling of Icinga/icinga-notifications#176.

Drop incident_history.caused_by_incident_history_id

---

application/controllers/ScheduleController.php
application/controllers/SchedulesController.php
application/forms/ScheduleForm.php
library/Notifications/Common/Links.php
library/Notifications/Model/Schedule.php
library/Notifications/Widget/ItemList/ScheduleList.php
library/Notifications/Widget/ItemList/ScheduleListItem.php

Move schedule to primary list

---

.github/workflows/phpstan.yml
library/Notifications/ProvidedHook/Notifications/ObjectsRenderer.php
library/Notifications/Widget/ItemList/EventListItem.php
library/Notifications/Widget/ItemList/IncidentListItem.php
phpstan-baseline-standard.neon
phpstan.neon
run.php

requires https://github.com/Icinga/ipl-web/pull/224

Provide `ObjectsRendererHook` for `icingadb`

---

application/controllers/ContactController.php

ContactController: Fix the retreival of contact full name during deletion

---

library/Notifications/Web/Form/ContactForm.php
phpstan-baseline-standard.neon

ContactForm: Fix saving and populating contact addresses

---

application/forms/ContactGroupForm.php
library/Notifications/Model/Contact.php
library/Notifications/Model/Contactgroup.php
library/Notifications/Web/Form/ContactForm.php
library/Notifications/Widget/MemberSuggestions.php
library/Notifications/Widget/RecipientSuggestions.php

resolves https://github.com/Icinga/icinga-notifications-web/issues/200
blocked by #183
blocked by https://github.com/Icinga/icinga-notifications/pull/218

Contact/Contactgroup: Remove usage of color column

---

library/Notifications/Web/Form/ContactForm.php

* for https://github.com/Icinga/icinga-notifications/pull/203#discussion_r1663976988

Limit contact.username and .contact_address length

---

doc/06-Desktop-Notifications.md
library/Notifications/Daemon/Server.php

Daemon\Server: Change default listen config

---

application/forms/ChannelForm.php

ChannelForm: Type bool (checkbox) option must be stored as bool in db

---

application/forms/ContactGroupForm.php

ContactGroupForm: Remove contact by clicking on it

---

application/controllers/SchedulesController.php

SchedulesController::getTabs(): Add missing `baseTagrget` to tabs

---

application/forms/RotationConfigForm.php

RotationConfigForm: Improve rotation time input

---

application/forms/RotationConfigForm.php

RotationConfigForm: Add new rotation at the bottom of the list

---

application/forms/RotationConfigForm.php

https://github.com/Icinga/icinga-notifications-web/pull/295 missed this change.

RotationConfigForm: Don't increase priority when editing a rotation

---

application/forms/RotationConfigForm.php
public/css/form.less

fixes changes mentioned in https://github.com/Icinga/icinga-notifications-web/pull/302

RotationConfigForm: Fix incorrect thumbnail descriptions and example

---

library/Notifications/Widget/Timeline.php
public/css/timeline.less

resolves:
- https://github.com/Icinga/icinga-notifications-web/pull/296#discussion_r2026517475
- https://github.com/Icinga/icinga-notifications-web/pull/296#discussion_r2026523509

Timeline: Add title to `drag-handle` of the rotation title and fix css

---

application/forms/AddEscalationForm.php
application/forms/AddFilterForm.php
application/forms/BaseEscalationForm.php
application/forms/EventRuleForm.php
application/forms/RemoveEscalationForm.php

Use 'addElement()' to add CSRF tokens and UID elements

---

public/css/timeline.less

Force line-break for days-header
